-- ═══════════════════════════════════════════════════════════════════
--  Personell per prosjekt + kontorkalender — sjå claude/framdrift-modul.md
--  («Personell og timar»). Køyr i Supabase SQL Editor. Trygt å køyre fleire
--  gonger.
-- ═══════════════════════════════════════════════════════════════════

-- Personar som arbeider på eit prosjekt. `prosent` = stillingsprosent på DETTE
-- prosjektet-grunnlaget for kapasitet (kontoret sine arbeidstimar per veke × prosent).
CREATE TABLE IF NOT EXISTS prosjekt_personell (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id  BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  namn        TEXT   NOT NULL,
  rolle       TEXT   DEFAULT '',
  prosent     NUMERIC DEFAULT 100,
  epost       TEXT   DEFAULT '',
  merknad     TEXT   DEFAULT '',
  sortering   INT    DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_prosjekt_personell_project ON prosjekt_personell(project_id);

ALTER TABLE prosjekt_personell ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "prosjekt_personell_select" ON prosjekt_personell;
DROP POLICY IF EXISTS "prosjekt_personell_insert" ON prosjekt_personell;
DROP POLICY IF EXISTS "prosjekt_personell_update" ON prosjekt_personell;
DROP POLICY IF EXISTS "prosjekt_personell_delete" ON prosjekt_personell;
CREATE POLICY "prosjekt_personell_select" ON prosjekt_personell FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "prosjekt_personell_insert" ON prosjekt_personell FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "prosjekt_personell_update" ON prosjekt_personell FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "prosjekt_personell_delete" ON prosjekt_personell FOR DELETE USING (auth.uid() = user_id);

-- Kontorkalender (arbeidstimar per dag, fridagar …) — éi rad per brukar.
CREATE TABLE IF NOT EXISTS kontor_kalender (
  user_id        UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  innstillingar  JSONB NOT NULL DEFAULT '{}',
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE kontor_kalender ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "kontor_kalender_select" ON kontor_kalender;
DROP POLICY IF EXISTS "kontor_kalender_insert" ON kontor_kalender;
DROP POLICY IF EXISTS "kontor_kalender_update" ON kontor_kalender;
CREATE POLICY "kontor_kalender_select" ON kontor_kalender FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "kontor_kalender_insert" ON kontor_kalender FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "kontor_kalender_update" ON kontor_kalender FOR UPDATE USING (auth.uid() = user_id);
