-- ═══════════════════════════════════════════════════════════════════
--  Framdrift-modulen (faseplan/Gantt per prosjekt) — sjå
--  claude/framdrift-modul.md. Køyr i Supabase SQL Editor. Trygt å køyre
--  fleire gonger.
--
--  ÉI rad per (brukar, prosjekt) med heile planen som JSONB-liste
--  (fasar, aktivitetar, milepælar, avhengnader). Medvite IKKJE i
--  projects.details: ProsjektModule skriv heile `details` tilbake frå
--  prosjektkortet ved lagring og ville overskrive framdriftsplanen med ei
--  gammal kopi.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS framdrift_planar (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id  BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  elementer   JSONB  NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_framdrift_planar_project ON framdrift_planar(project_id);

ALTER TABLE framdrift_planar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "framdrift_planar_select" ON framdrift_planar;
DROP POLICY IF EXISTS "framdrift_planar_insert" ON framdrift_planar;
DROP POLICY IF EXISTS "framdrift_planar_update" ON framdrift_planar;
DROP POLICY IF EXISTS "framdrift_planar_delete" ON framdrift_planar;
CREATE POLICY "framdrift_planar_select" ON framdrift_planar FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "framdrift_planar_insert" ON framdrift_planar FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "framdrift_planar_update" ON framdrift_planar FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "framdrift_planar_delete" ON framdrift_planar FOR DELETE USING (auth.uid() = user_id);
